language: python
python:
  - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y fglrx opencl-headers
install:
  - pip install -r requirements.txt
script: PRINT_INFO=1 nosetests -s .
